#!/usr/bin/env bash
# Creates the Proxmox API token this repo's OpenTofu configuration authenticates with,
# and writes it to tofu/terraform.tfvars (gitignored).
#
# Run as your normal user, NOT under sudo — the script calls sudo only for the pveum
# command, so the tfvars file ends up owned by you rather than by root.
#
# Implements tasks 2.1-2.3 of the bootstrap-k3s-node change.
# See design.md D4: this token is deliberately attached to root@pam and is a recorded,
# time-boxed shortcut. Replacing it with a scoped terraform@pve user and a minimal role
# belongs to the secrets milestone.
set -euo pipefail

TOKEN_USER="${TOKEN_USER:-root@pam}"
TOKEN_ID="${TOKEN_ID:-tofu}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TFVARS="$REPO_ROOT/tofu/terraform.tfvars"
RECREATE=0
FORCE=0

usage() {
  cat <<'USAGE'
usage: create-proxmox-token.sh [--recreate] [--force]

  --recreate  Delete an existing token of the same name and issue a new one.
              The old secret stops working immediately.
  --force     Overwrite tofu/terraform.tfvars even if it already defines a token.

Environment overrides: TOKEN_USER (default root@pam), TOKEN_ID (default tofu).
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --recreate) RECREATE=1 ;;
    --force)    FORCE=1 ;;
    -h|--help)  usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

die() { echo "error: $*" >&2; exit 1; }

[ "${EUID:-$(id -u)}" -ne 0 ] || die "run as your normal user, not under sudo (see header)"

PVEUM="$(command -v pveum || echo /usr/sbin/pveum)"
[ -x "$PVEUM" ] || die "pveum not found — is this the Proxmox host?"

# Detect the node name and API endpoint rather than hardcoding them.
NODE="$(hostname -s)"
HOST_IP="$(ip -4 -o addr show vmbr0 2>/dev/null | awk '{print $4}' | cut -d/ -f1)"
[ -n "$HOST_IP" ] || die "could not determine the vmbr0 address"
ENDPOINT="https://${HOST_IP}:8006/"

echo "node:     $NODE"
echo "endpoint: $ENDPOINT"
echo "token:    ${TOKEN_USER}!${TOKEN_ID}"
echo

# Guard the tfvars file before creating anything, so a refusal here does not leave an
# orphaned token behind.
if [ -f "$TFVARS" ] && grep -q '^[[:space:]]*proxmox_api_token' "$TFVARS" && [ "$FORCE" -eq 0 ]; then
  die "$TFVARS already defines proxmox_api_token — pass --force to overwrite"
fi

echo "requesting sudo for pveum..."
sudo -v || die "sudo authentication failed"

token_exists() {
  sudo "$PVEUM" user token list "$TOKEN_USER" --output-format json 2>/dev/null \
    | python3 -c "import json,sys;print(any(t.get('tokenid')==sys.argv[1] for t in json.load(sys.stdin)))" "$TOKEN_ID" \
    2>/dev/null | grep -q True
}

if token_exists; then
  [ "$RECREATE" -eq 1 ] || die "token ${TOKEN_USER}!${TOKEN_ID} already exists (its secret cannot be re-read) — pass --recreate to replace it"
  echo "removing existing token ${TOKEN_USER}!${TOKEN_ID}"
  sudo "$PVEUM" user token remove "$TOKEN_USER" "$TOKEN_ID" >/dev/null
fi

# --privsep 0 is essential: with privilege separation on (the default) the token
# inherits no permissions and every API call fails with a 403 that reads like a bad
# secret. This is the most common way this step goes wrong.
echo "creating token..."
TOKEN_JSON="$(sudo "$PVEUM" user token add "$TOKEN_USER" "$TOKEN_ID" --privsep 0 --output-format json)"

read -r FULL_ID SECRET PRIVSEP <<<"$(printf '%s' "$TOKEN_JSON" | python3 -c "
import json,sys
d=json.load(sys.stdin)
info=d.get('info') or {}
if isinstance(info,str): info=json.loads(info)
print(d.get('full-tokenid',''), d.get('value',''), info.get('privsep','?'))
")"

[ -n "$FULL_ID" ] && [ -n "$SECRET" ] || die "could not parse the token from pveum output"
[ "$PRIVSEP" = "0" ] || die "token was created with privilege separation enabled (privsep=$PRIVSEP) — remove it and re-run"

# Write with a restrictive umask so the secret is never briefly world-readable.
mkdir -p "$(dirname "$TFVARS")"
( umask 077
  cat > "$TFVARS" <<TFVARS_EOF
# Generated by scripts/create-proxmox-token.sh — DO NOT COMMIT.
# Covered by .gitignore. Regenerate with --recreate if the secret is lost.

proxmox_endpoint  = "${ENDPOINT}"
proxmox_node      = "${NODE}"
proxmox_api_token = "${FULL_ID}=${SECRET}"
TFVARS_EOF
)
chmod 600 "$TFVARS"

# Task 2.3: prove the token works against the API before OpenTofu is involved, so an
# auth failure cannot be mistaken for a provider problem. --insecure because the host
# serves its own certificate.
echo "verifying token against the API..."
HTTP_CODE="$(curl -sS --insecure -o /dev/null -w '%{http_code}' \
  -H "Authorization: PVEAPIToken=${FULL_ID}=${SECRET}" \
  "${ENDPOINT}api2/json/nodes" || true)"

unset SECRET TOKEN_JSON

case "$HTTP_CODE" in
  200) echo "  OK — API returned 200" ;;
  401) die "API returned 401: the token was rejected" ;;
  403) die "API returned 403: token authenticated but lacks permissions — check privsep" ;;
  000) die "could not reach ${ENDPOINT} — is the Proxmox API listening?" ;;
  *)   die "unexpected HTTP status $HTTP_CODE from the API" ;;
esac

echo
echo "wrote $TFVARS (mode 600, gitignored)"
git -C "$REPO_ROOT" check-ignore -q "$TFVARS" \
  && echo "confirmed: git ignores it" \
  || echo "WARNING: git does NOT ignore $TFVARS — do not commit"
